api_platform:
    title: Zone51 API
    version: 1.0.0
    # Good defaults for REST APIs
    formats:
        json: ['application/json']
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
    defaults:

        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
